import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "../app/_components/ui/sonner"
import Footer from "./_components/footer"
// import AuthProvider from "./_providers/auth"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark h-full">
      <body className={`${inter.className} flex h-full flex-col`}>
        {/* <AuthProvider> */}
        <main className="flex-1">{children}</main>
        {/* </AuthProvider> */}

        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
